### ISSUE TITLE
Screenshots or gifs

### ISSUE THREAD

**Issue by mikaelmello** [CasterKKK/flutter_realworld_app#5]
I"d like to take a look at the app without having to download and build it myself, could you do that? Thanks

**Comment by lastlink** [comment]
Mobile is more difficulty b/c of licensing, while a build of the apk (android) is possible, the ios isn't without a paid license.

**Comment by mikaelmello** [comment]
How is that related to simply taking screenshots of the app?

**Comment by lastlink** [comment]
I couldn't tell if your question was to look at the app or for screenshots. 


![simulator screen shot - iphone 7 - 2019-01-07 at 20 22 55](https://user-images.githubusercontent.com/6679425/50804099-8ec4f400-12ba-11e9-9869-1f28f3e72627.png)
![simulator screen shot - iphone 7 - 2019-01-07 at 20 23 16](https://user-images.githubusercontent.com/6679425/50804101-8ec4f400-12ba-11e9-8a53-d21fd6d8b730.png)
![simulator screen shot - iphone 7 - 2019-01-07 at 20 23 20](https://user-images.githubusercontent.com/6679425/50804102-8ec4f400-12ba-11e9-82ce-aff7c32fb479.png)

**Comment by UkonnRa** [comment]
@lastlink  thank you~ help a lot~

**Comment by mikaelmello** [comment]
The app really does look nice. I'll close the issue, I'd recommend to put these screenshots in the README

**Comment by lastlink** [comment]
@mikaelmello you're welcome to do a pull request and add the links from these uploaded images
